import wb_logo from '../../assets/icons/wb.png'
import wallpapers from '../../assets/images/wallpapers.jpg'
import braw_wallpapers from '../../assets/images/braw_wallpaper.jpg'
import robot from '../../assets/images/robot_uniforme.jpg'
import robot_dos from '../../assets/images/robot_dos.png'
import icon_ai from '../../assets/images/icon_ai.png'
import icon_app from '../../assets/images/icon_app.png'
import icon_web from '../../assets/images/icon_web.png'
import icon_nube from '../../assets/images/icon_nube.png'
import icon_digital from '../../assets/images/icon_digital.png'
export { wb_logo, wallpapers, braw_wallpapers, robot, robot_dos, icon_ai, icon_app, icon_web,icon_nube,icon_digital }
